name: Run project tests
on:
  push:
    branches: [ci]
  workflow_dispatch:

jobs:
  # Label of the container job
  install_nest:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task-api
    # Service containers to run with `container-job`
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        # options: --health-cmd "mongo --version" --health-interval 10s --health-timeout 5s --health-retries 3
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: task

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install golang
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.0"

      - run: |
          cd test    
          go mod download
          go test -v

      - name: Run the server
        run: |
          pnpm run start &
          sleep 5
        env:
          MONGO_URL: mongodb://root:task@localhost
          insecure: true
          JAEGER_URL: "http://localhost:4318/v1/traces"
          HEALTH_PORT: 3003
          AUTH_API_URL: "localhost:4002"
          PORT: 5004
